version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongoInit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    image: node:24-slim
    container_name: api
    command: npm run dev:api
    working_dir: /usr/src/app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  worker:
    image: node:24-slim
    container_name: worker
    command: npm run dev:worker
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
